### ISSUE TITLE
Parse index.md files into index.yaml

### ISSUE THREAD

**Issue by dandhlee** [googleapis/sphinx-docfx-yaml#105]
Googlers see b/200623336.

The autogenerated `index.md` files are quite useful entry pages into each client libraries. However since `index.yaml` already exists from the plugin, we should merge the content of the two together.

**Comment by tbpg** [comment]
Alternatively, we could rename one of them?

**Comment by dandhlee** [comment]
I think it would be a better experience to incorporate both into one file. Current `index.yaml` page can seem somewhat empty, which parsing the new `index.md` content could help in this aspect. Having two separate pages I think would make the user experience much more confusing if we could consolidate this into one.

**Comment by dandhlee** [comment]
Relevant work required for #106, raising the priority for this issue as well.
