### ISSUE TITLE
FR: Python 3.10+ support

### ISSUE THREAD

**Issue by tswast** [googleapis/sphinx-docfx-yaml#305]
We are less than 1 year until projects such as pandas and numpy drop support for Python 3.9 on April 5, 2024. See: https://numpy.org/neps/nep-0029-deprecation_policy.html#support-table

I'd love to make sure we support Python 3.10+ in time that packages in that ecosystem can continue to use docfx for documentation generation.

**Comment by dandhlee** [comment]
Will work on it this week, the major blocker is Sphinx version which currently sits at 4.5.0, and the latest is at major version 7. However, getting all of the tools to work with 7 was tough and I haven't been able to look at the plugin until now.

The jump from 4 -> 7 will be harder to fix, so for now I'll try to see if I can get it updated to be compatible with 3.10/3.11 with 5.3.0 version, and then work towards upgrading to the latest version (or just pinning it for now until we need to upgrade further).
