### ISSUE TITLE
Allow generate-docs Kokoro job to run for multi-version releases on failures

### ISSUE THREAD

**Issue by dandhlee** [googleapis/sphinx-docfx-yaml#31]
Currently, it is likely expected for the `generate-docs` Kokoro job to fail on multi-version releases when given the option for `GITHUB_TAG=all` is given. While the option is supported and will retrieve all the tags and run against all releases, there probably are releases where it doesn't have nox builds for `docs` or `docfx` jobs which would fail the run prematurely.

This issue should be closed if the Kokoro job doesn't fail on all the tags for every repo, or once it is updated to not fail on the tags (should skip on tags that we don't expect it to be upgraded on).

**Comment by dandhlee** [comment]
Testing on Spanner, it fails on `1.17.1` tag since it's missing docfx. Will need to look into skipping the ones that fail.

**Comment by tbpg** [comment]
We should be able to generate docs for every version, not just the ones where the DocFX or the docs job was already set up.

**Comment by dandhlee** [comment]
That gives me an idea on how to work with this :O
Hypothesis: take the docfx setup, and apply only the relevant files from each version tag release. This should work for all versions that's simply missing docfx setup. This may not work for earlier versions that doesn't use Sphinx. Seems like the easiest first approach to take, will investigate further.
